Update ios.yml

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -14,7 +14,7 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
-      
+
     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
@@ -32,18 +32,25 @@ jobs:
 
     - name: Install Fastlane
       run: gem install fastlane -NV
-      
+
     - name: Deploy to TestFlight
-      run: fastlane deploy_to_testflight
+      run: |
+        set -e
+        fastlane deploy_to_testflight
       env:
         FASTLANE_APPLE_ID: ${{ secrets.APPLE_DEVELOPER_USERNAME }}
         FASTLANE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
         FASTLANE_API_KEY: ${{ secrets.APPLE_API_KEY }}
         APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
         APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
-        
+
     - name: Archive Production Artifacts
+      if: success()
       uses: actions/upload-artifact@v2
       with:
         name: ios-app
         path: ./cordova/platforms/ios/build/device/**/*.ipa
+
+    - name: Notify if Deployment Fails
+      if: failure()
+      run: echo "Deployment to TestFlight failed."
